language: python

os:
  - linux
  - osx

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "nightly"

sudo: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then
      travis_retry sudo apt-get update -qq;
      sudo apt-get install python-pip -y;
    fi
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then
      travis_retry brew update;
      brew install python;
      brew install pyenv-virtualenv
      brew install pip;
    fi

install:
  make install

script:
  make test

notifications:
  email: false

exclude:
  - os: osx

# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End: